services:
  - type: web
    name: yolov8-backend
    runtime: python
    buildCommand: pip install -r requirements.txt -f https://download.pytorch.org/whl/cpu
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "TRUE"
