services:
  - type: web
    name: yolov8-backend
    runtime: python
    buildCommand: |
      pip install torch==2.1.0+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "TRUE"
